# Generated by Django 3.2.7 on 2021-10-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_eventlist_costtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfreetime',
            old_name='freetime',
            new_name='freeTime',
        ),
        migrations.RenameField(
            model_name='dailyfreetime',
            old_name='timedate',
            new_name='timeDate',
        ),
        migrations.RenameField(
            model_name='dailyfreetime',
            old_name='username',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='costtime',
            new_name='costTime',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='eventdate',
            new_name='eventDate',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='eventname',
            new_name='eventName',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='iscomplete',
            new_name='isComplete',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='predtime',
            new_name='predTime',
        ),
        migrations.RenameField(
            model_name='eventlist',
            old_name='username',
            new_name='userName',
        ),
    ]
