# Generated by Django 3.2.7 on 2021-10-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_dailyfreetime_busytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfreetime',
            name='busytime',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
